import fs from 'node:fs';import assert from 'node:assert/strict';
import {compute,createMatch,beginTurn,resolve,roundEven} from '../dist/engine.js';
import {chooseCpu} from '../dist/cpu.js';
const data=JSON.parse(fs.readFileSync(new URL('../dist/cards.json',import.meta.url))),source=JSON.parse(fs.readFileSync(new URL('./engine-fixtures.json',import.meta.url)));
let assertions=0;const equal=(a,b,label)=>{assert.deepEqual(a,b,label);assertions++;};
for(const f of source){const a=f.inputs,attacks=id=>data.cards[id].atk;const x={attacks:[attacks(a[0]),attacks(a[1])],moves:a.slice(2,4),types:[a[4]<0?0:data.cards[a[6+a[4]]].type,a[5]<0?0:data.cards[a[9+a[5]]].type],hp:a.slice(12,14),poison:a.slice(14,16),mask:a[16],berserk:a.slice(17,19),ssr:[[a[19],a[20]],[a[21],a[22]]],due:a.slice(23,25),growth:[a.slice(25,28),a.slice(28,31)]};const r=compute(x,data.engine);
const outputs={resultRoundWinner:r.roundWinner,resultRevealTactic1:a[4]<0?-1:a[6+a[4]],resultRevealTactic2:a[5]<0?-1:a[9+a[5]],resultDamageToP1:r.damage[0],resultDamageToP2:r.damage[1],resultHp1:r.hp[0],resultHp2:r.hp[1],resultMatchWinner:r.matchWinner,resultPoisonTarget:r.poisonTarget,resultRevengeTargetMask:r.revengeMask,resultSleepTargetMask:r.sleepMask,resultBerserkTargetMask:r.berserkMask,resultForetellTarget:r.foretellTarget,resultForetellAmount:r.foretellAmount};equal(outputs,f.outputs,'Unity Compute fixture');}
let rounds=0;
for(const game of JSON.parse(fs.readFileSync(new URL('./round-fixtures.json',import.meta.url)))){const state=createMatch(data,game.characters,game.decks);for(const step of game.turns){beginTurn(state,data);let roll=0;const r=resolve(state,data,step.moves,step.slots,()=>step.rolls[roll++]),e=step.expected,s=state.sides;
equal(s.map(x=>x.hp),e.hp,'HP');equal(state.winner,e.winner,'winner');equal(r.roundWinner,e.roundWinner,'attribute winner');equal(r.damage,e.damage,'damage');equal(r.learnMask,e.learnMask,'learn mask');equal(s.map(x=>x.deck.map(d=>d.id)),e.deck,'copied deck');equal(s.map(x=>x.deck.map(d=>d.left)),e.rem,'remaining uses');equal(s.map(x=>x.growth),e.growth,'Mine growth');equal(s.reduce((m,x,i)=>m|((x.revenge>0?1:0)|(x.sleep>0?2:0)|(x.berserk.length?4:0))<<(i*3),0),e.mask,'status mask');equal(s.map(x=>x.poison.left?x.poison.amount:0),e.poison,'poison');equal(s.map(x=>x.poison.left),e.poisonRem.map(x=>Math.max(...x)),'poison duration');equal(s.map(x=>x.transformed?1:0).reduce((v,n,i)=>v|(n<<i),0),e.ssr,'SSR');for(let i=0;i<2;i++)equal(s[i].foretell.map(x=>`${x.left}:${x.amount}`).sort(),e.foretellRem[i].map((v,k)=>v>0?`${v}:${e.foretellAmt[i][k]}`:null).filter(Boolean).sort(),'foretell');rounds++;}}
const test=createMatch(data,[160,161],[[0,1,2],[11,12,13]]);beginTurn(test,data);const original=JSON.stringify(test);assert.throws(()=>resolve(test,data,[9,0],[-1,-1]));equal(JSON.stringify(test),original,'invalid action is atomic');
const same=structuredClone(test);same.sides[0].deck=[{id:10,left:1},{id:20,left:1},{id:30,left:1}];equal(chooseCpu(test,data,()=>.4),chooseCpu(same,data,()=>.4),'CPU ignores hidden opponent deck');equal(JSON.stringify(test),original,'CPU does not mutate match');
equal([roundEven(2.5),roundEven(3.5),roundEven(-2.5)],[2,4,-2],'Unity rounding');
console.log(`PASS: ${source.length} Unity input cases + ${rounds} full-match turns, ${assertions} assertions; CPU hidden-information and input checks passed.`);
